4_5-inline_formset
thinknetica-django-lab-03/dasfq pull request #44
Opened 2021-06-12 09:36 UTC by dasfq

Closes #20 

Опять намудрил с git, поэтому UpdateView попала уже в следующую ветку 4_6

2021-06-12 22:06 UTC, mikhailborodin requested changes

2021-06-12 22:06 UTC, mikhailborodin commented on ecommerce/ecommerce/main/views.py
> +        context['picture_formset'] = PictureFormSet()
в шаблоне ожидается inline_formset а не picture_formset

2021-06-12 22:06 UTC, mikhailborodin commented on ecommerce/ecommerce/main/forms.py
> +CarFormSet = modelformset_factory(
CarFormSet не нужен

2021-06-15 15:51 UTC, dasfq commented on ecommerce/ecommerce/main/views.py
> +        context['picture_formset'] = PictureFormSet()
исправил

2021-06-15 15:51 UTC, dasfq commented on ecommerce/ecommerce/main/forms.py
> +CarFormSet = modelformset_factory(
убрал

2021-06-16 06:53 UTC, mikhailborodin approved these changes

2021-06-16 10:53 UTC, merged