4_6_check_ages
thinknetica-django-lab-03/dasfq pull request #45
Opened 2021-06-12 09:37 UTC by dasfq

Closes #26

2021-06-12 22:08 UTC, mikhailborodin requested changes

2021-06-12 22:08 UTC, mikhailborodin commented on ecommerce/ecommerce/main/views.py
> +        context['inline_formset'] = PictureFormSet()
теперь в шаблоне picture_formset, а здесь вы в inline_formset кладете набор форм

2021-06-15 15:53 UTC, dasfq commented on ecommerce/ecommerce/main/views.py
> +        context['inline_formset'] = PictureFormSet()
Исправил в шаблоне

2021-06-16 06:53 UTC, mikhailborodin approved these changes

2021-06-16 10:54 UTC, merged