5.1 Login required
thinknetica-django-lab-03/dasfq pull request #46
Opened 2021-06-12 10:38 UTC by dasfq

Closes #33

2021-06-12 22:23 UTC, mikhailborodin requested changes

2021-06-12 22:23 UTC, mikhailborodin commented on ecommerce/ecommerce/ecommerce/settings.py
> +LOGIN_URL = '/admin/login/?next=/admin/'
надо ещё на урлы добавить метод login_required или в CBV добавить специальный миксин, чтобы страницы были доступны только авторизованным пользователям

2021-06-15 15:35 UTC, dasfq commented on ecommerce/ecommerce/ecommerce/settings.py
> +LOGIN_URL = '/admin/login/?next=/admin/'
дак у меня вроде же добавлен LoginRequiredMixin в ProfileUpdateView ? Или ещё какой то другой нужно добавить?

2021-06-16 06:54 UTC, mikhailborodin approved these changes

2021-06-16 10:54 UTC, merged