7_3_reading
thinknetica-django-lab-03/dasfq pull request #82
Opened 2021-07-03 17:51 UTC by dasfq

Closes #55 
Прочитал мануал.

2021-07-03 21:29 UTC, mikhailborodin requested changes

2021-07-03 21:29 UTC, mikhailborodin commented on ecommerce/ecommerce/main/views.py
>  def IndexView(request):
не вижу чтобы задача 7.3 была решена

2021-07-04 16:12 UTC, dasfq commented
Извиняюсь, не увидел, что в задании есть Задача )
В общем, перенёс отправку письма из Signals в delay().
Чтобы передать объект нового объявления в функцию .delay() пришлось его перевести model_to_dict. Может есть способ передать сам объект, а не словарь?

2021-07-04 21:06 UTC, mikhailborodin commented
> Извиняюсь, не увидел, что в задании есть Задача )
> В общем, перенёс отправку письма из Signals в delay().
> Чтобы передать объект нового объявления в функцию .delay() пришлось его перевести model_to_dict. Может есть способ передать сам объект, а не словарь?

особенность работы брокеров сообщений такова, что данные они могут принимать только в сериализованном виде

2021-07-04 21:07 UTC, mikhailborodin approved these changes

2021-07-08 18:10 UTC, merged